#!/usr/bin/env bash
# Record what is installed on this machine.
#
# The package lists themselves are generated by src/generate/package-lists.ts;
# pass names to that script directly to refresh only some of them.
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

bun run "$SCRIPT_DIR/src/generate/package-lists.ts"

# gup keeps its own manifest of go-installed binaries.
gup export
